### ISSUE TITLE
How to determine the corresponding value of each trinucleotide?

### ISSUE THREAD

**Issue by HaoxuanJin** [judithabk6/clonesig#2]
Hey guys, thank you for your great efforts on **`CloneSig`**. A wonderful idea to analyze tumor heterogeneity by combining mutation frequency and its trinucleotide signature.

However, while preparing the input file, I am not sure how to determine the corresponding value of each trinucleotide? Like what is the trinucleotide value for `ACA` mutation? Can you describe specifically for this or add a function to convert trinucleotide type into corresponding trinucleotide value?

Thank you for your effort again and looking forward to your reply.

**Comment by judithabk6** [comment]
Dear HaoxuanJin,

Thank you for your interest in using **`CloneSig`**.
I have slightly automatizes the process myself when dealing with the TCGA by considering the trinucleotides in the format `A[C>T]A`for instance, with `C` the reference nucleotide and `T` the variant.

We have defined an ordered list of all 96 possible patterns, with the same order as COSMIC etc (`PAT_LIST`, importable from the `CloneSig` package), and a small helper function (`get_context`, importable from the `CloneSig` package) that constructs the trinucleotide in the right format using the `CONTEXT` variable from the TCGA data and constructed `ref` and `alt` variables. The `CONTEXT` variable contains the mutated position and 5 flanking nucleotides on each side.

A full [example code](https://github.com/judithabk6/Clonesig_analysis/blob/master/signature_code/run_clonesig_tcga.py) is the one used to deal with the TCGA data that you can adapt to your use case.

Here is the extract that can be of use for you
```python
import pandas as pd
from clonesig.data_loader import get_context, PAT_LIST

# open snv_table etc.
# get trinucleotide in the A[C>T]A form
snv_table = snv_table.assign(
        pattern=pd.Categorical(
            snv_table.apply(get_context, axis=1),
            categories=PAT_LIST, ordered=True))
# assign the right index
snv_table = snv_table.assign(
        trinucleotide=snv_table.apply(lambda x: PAT_LIST.index(x['pattern']), axis=1))
```

Depending on your data, just adapting the `get_context` function to your specific case should help.

I hope that helps and feel free to ask for more details if needed, or provide the format of your data if you want me to work with you on the exact way to do it properly.

and thanks a lot your your question! I will try to update the documentation, it will be of help for everyone.

**Comment by HaoxuanJin** [comment]
Thank you, judithabk6!

Sorry for the late reply. It took me a few days to test `CloneSig` and solved other bugs.

`PAT_LIST` is exactly what I need! And the result on my data looks wonderful.

Thank you for your help and looking forward to the upgrade of `CloneSig`.

BTW, hope the coronavirus away from you and everyone.
