### ISSUE TITLE
Does the package work on python 3?

### ISSUE THREAD

**Issue by zeyad-kay** [judithabk6/clonesig#6]
The setup.py mentions that the package works on python 3, yet it fails when trying to install. I tried it on python 2 and it works perfectly fine. So is it a typo in the setup.py or am i missing something?

**Comment by judithabk6** [comment]
I have just re-tested it in a new virtual environment, and the installation worked perfectly with Python 3.7.11. What error did you get with the install?

**Comment by zeyad-kay** [comment]
it outputs 
```sh
ERROR: Command errored out with exit status 1:
command: /home/zeyad/test/.venv/bin/python3 -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-req-build-3ke42rls/setup.py'"'"'; __file__='"'"'/tmp/pip-req-build-3ke42rls/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d /tmp/pip-wheel-es3olz1k
       cwd: /tmp/pip-req-build-3ke42rls/
  Complete output (6 lines):
  usage: setup.py [global_opts] cmd1 [cmd1_opts] [cmd2 [cmd2_opts] ...]
     or: setup.py --help [cmd1 cmd2 ...]
     or: setup.py --help-commands
     or: setup.py cmd --help

  error: invalid command 'bdist_wheel'
  ERROR: Failed building wheel for clonesig
```


It also outputs the same error for all dependencies (numpy, pandas, etc...).

python version: 3.8.10

**Comment by judithabk6** [comment]
In that case it seems to be rather a problem with your python installation. I am not sure what is going on exactly, but a quick search seems to suggest that installing the wheel package (`pip install wheel`) might help

**Comment by zeyad-kay** [comment]
Just tried and it didn't work. I think the python installation is fine as I am testing it on a remote virtual machine on azure.

**Comment by judithabk6** [comment]
OK. Just tried with python 3.8.10 and I also got the error. It seems that pandas 0.24.2 can't install. I'll look into it later to have a proper fix, I'll let you know.
In the meantime, it works with python 3.7
Thanks for bringing this to my attention!
